### ISSUE TITLE
error while click sidebar

### ISSUE THREAD

**Issue by sharing-sense** [quarkcms/quark-ui#1]
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `DashboardPage`. See https://fb.me/react-warning-keys for more information.
    in withConfigConsumer(Statistic) (at DashboardPage.tsx:144)
    in DashboardPage (created by ConnectFunction)
    in ConnectFunction (at Index.tsx:15)

devScripts.js:5836 Warning: Encountered two children with the same key, `.$/quark/engine`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in ul (created by DOMWrap)
    in DOMWrap (created by SubPopupMenu)
    in SubPopupMenu (created by Connect(SubPopupMenu))
    in Connect(SubPopupMenu) (created by CSSMotion)
    in CSSMotion (created by ForwardRef)
    in ForwardRef (created by SubMenu)
    in li (created by SubMenu)
    in SubMenu (created by Connect(SubMenu))
    in Connect(SubMenu) (created by Context.Consumer)
    in SubMenu (created by BaseMenu)
    in ul (created by DOMWrap)
    in DOMWrap (created by SubPopupMenu)
    in SubPopupMenu (created by Connect(SubPopupMenu))
    in Connect(SubPopupMenu) (created by Menu)
    in Provider (created by Menu)
    in Menu (created by Context.Consumer)
    in InternalMenu (created by Context.Consumer)
    in Menu (created by BaseMenu)
    in BaseMenu (created by SiderMenu)

**Comment by tangtanglove** [comment]
安装完成后，用npm指定一下版本：`npm install @umijs/route-utils@1.0.17 --save`，这个是umijs的一个bug，暂时先这样解决，等待官方修复。
