### ISSUE TITLE
建议提供所见即所得生成json并实现低代码效果的实例

### ISSUE THREAD

**Issue by fengnex** [quarkcms/quark-ui#7]
如题，都2.0版本了，应该提供支持在线拖拽、调整组件属性来生成json schema的工具了吧
再支持根据上面生成的json，证明低代码方面的效果，证明可以并很值得用于实际业务开发。
期待看到这些效果能成为现实！
也期待看到更多相关的功能、特性~~~

**Comment by tangtanglove** [comment]
嗯，是这个规划，一个人开发进度太慢，欢迎加入。

**Comment by tangtanglove** [comment]
现在来说可以通过mock看展示效果，后续完善文档。

**Comment by fengnex** [comment]
一个人确实不容易，前几天看了https://designable-antd.formilyjs.org/，
发现formily和ahooks都不错，不知道能否集成。
时间上不知道能否抽得出。

**Comment by fengnex** [comment]
相比mock，其实我更喜欢spring boot或go做个后端来配合前端，用sqlite或MySQL、redis，已经挺方便的了

**Comment by tangtanglove** [comment]
暂时提供了Laravel（PHP）框架的扩展；spring boot和go不太熟悉，有精力的话会跟进。

**Comment by fengnex** [comment]
不怎么懂php，周围搞php的几乎没有，后面有空研究下

**Comment by tangtanglove** [comment]
formily刚才看了，感觉还行，有时间了我研究一下，最近也在找这种拖拽的解决方案。
